### ISSUE TITLE
Transfer user profile data 

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/talao-wallet#102]

**Comment by ThierryThevenet** [comment]
L idee c est un self issued credential basé sur les données du profil enregistré sur le téléphone
je dois travailler sur le json

**Comment by ThierryThevenet** [comment]
voila le json LD
https://github.com/TalaoDAO/wallet-tools/blob/main/test/CredentialOffer2/SelfIssued.jsonld

lorsque l utilisateur met a jour ses données persos le verifibale credential est emis par lui meme (didkit.issue_verfiiable credential) et il est sauvegardé. IL faudrait lui proposer ce créer ce premier credential à l onboarding sans que cela soit obligatoire

**Comment by ThierryThevenet** [comment]
attention les attributs vides ne doivent pas apparaitre dans un VC

**Comment by hawkbee1** [comment]
didkit.issue_verfiiable credential is the function to use.

**Comment by hawkbee1** [comment]
@ThierryThevenet we don't see didkit.issue_verfiiable should we use didkit_vc_issue_credential ? 

In the flutter package we have the function:
```dart
static String issueCredential(String credential, String options, String key) {
    final vc = issue_credential(
        credential.toNativeUtf8(), options.toNativeUtf8(), key.toNativeUtf8());
    if (vc.address == nullptr.address) throw lastError();
    final vc_string = vc.toDartString();
    free_string(vc);
    return vc_string;
  }
```
do you know if we should call issueCredential with specific options ?

**Comment by ThierryThevenet** [comment]
Here's an example with direct call to DidKit: https://github.com/spruceid/didkit/blob/main/lib/flutter/test/didkit_test.dart
