### ISSUE TITLE
Voucher

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/talao-wallet#115]
c est pou run demo le VC est  là
https://github.com/TalaoDAO/wallet-tools/blob/main/test/CredentialOffer2/Voucher.jsonld

il faudrait pouvoir y ajouter une image avec la valeur du discount dessus

**Comment by ThierryThevenet** [comment]
![cryptovoucher-4x3-1](https://user-images.githubusercontent.com/32768069/148534933-98b7606c-05d6-4dd8-a27e-d06fa6eac989.png)

**Comment by hawkbee1** [comment]
@ThierryThevenet Je garde l'inclinaison du voucher dans la nouvelle version ?
![tz-voucher](https://user-images.githubusercontent.com/49282360/149808308-a505ec9f-0be3-4563-823c-f2e7108bad51.png)
