### ISSUE TITLE
design ecran "general infiormation"

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/talao-wallet#119]
L affichage est un peu moyen
![File(3)](https://user-images.githubusercontent.com/32768069/149659582-e39991aa-7b7a-40a6-a088-eee352c14230.jpg)

**Comment by ThierryThevenet** [comment]
lorsque l on ouvre la prmeiere fois le general information, on a un ecran gris @hawkbee1

**Comment by hawkbee1** [comment]
Ok je vois le soucis, je corrige dans 20 min.
