### ISSUE TITLE
application freezing during transition between splash screen and credential list on ios phone

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/talao-wallet#123]
Qd il y a beaucoup de VC , l app stop entre 2 ecrans. il semble qu'elle attende le chargement des VC...
When there is a lot of VC, app is freezing between two screens. It looks like app is waiting for credential list loading...
![File(4)](https://user-images.githubusercontent.com/32768069/150963393-870ad8e8-3653-46f4-9611-cdcda4f123c9.jpg)
C

**Comment by hawkbee1** [comment]
I wasn't able to reproduce the same issue on ios emulator. Later, with Bibash help we can probably have more information thanks to his physical ios device. For now, next build will contains two changes : 
- A build parameter for slow animation,
- App will wait complete credential list loading before opening credential list page.

The second change will also help us display information/help for first time users.

**Comment by hawkbee1** [comment]
Splash Screen should be visible during one second at least
