### ISSUE TITLE
IPFS, update des liens

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/talao-wallet#124]
il faudraot pouvoir accepte dans les liens sur les VC, un type de lien 
"ipfs://QmdLtDkAEgiQz29CJob8edtZ4FuDyWEZe2UN4kftx5AdUF"
de maniere a ce que le chemin d acces soit calculé avec le gateway au choix du verifier et non pas celui imposé par Talao
donc etre en lmesure d 'accepter les 2 liens possibles

https://gateway.pinata.cloud/ipfs/QmXdKFQDoGpKRb11aj84zmmYXuTNpe7TYaJs9z6b9QN2VM
ipfs://QmXdKFQDoGpKRb11aj84zmmYXuTNpe7TYaJs9z6b9QN2VM

et mettre https://gateway.pinata.clou dans une variable

**Comment by ThierryThevenet** [comment]
j aurais du y penser plutot !

**Comment by hawkbee1** [comment]
duplicate of #207
