### ISSUE TITLE
Losing Credential when updating app.

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/talao-wallet#129]

**Comment by ThierryThevenet** [comment]
j ai effaçé l app IOS et je l ai recharcgé. IL Iy a avait encore le meme DID mais les credentials avaient disparus
il me semble que ce n'étais pas  le cas avant.

**Comment by hawkbee1** [comment]
I deleted ios app and installed it again. It still had the DID (key) but credentials disappeared .
I think it wasn't the case before.

**Comment by hawkbee1** [comment]
DID is stored with flutter_secure_storage package  ^5.0.2
Credentials are stored with sembast: ^3.1.1+1
