### ISSUE TITLE
Creer un repo specifique pour respecter le grant de Tezos

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/talao-wallet#28]

**Comment by hawkbee1** [comment]
@ThierryThevenet Je me suis contenté de changer la branche par défaut dans notre repo : main -> dev-talao.
Est-ce que çà suffit pour répondre au besoin ?

**Comment by hawkbee1** [comment]
proposition de nouveau nom pour le repo : talao-wallet

**Comment by ThierryThevenet** [comment]
ok
