### ISSUE TITLE
utilisation  de did:key a la place de did:tz

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/talao-wallet#34]
C est un sujet important parcque certain client ne peuvent pas supporter le modele de signature did:tz de la blockchain Tezos

Si j ai bien compris le mode de génération de la clé de cryptage de Credible, il suffirait de changer la valeur de la variable defaultDIDMethod .

https://github.com/TalaoDAO/credible/blob/main/lib/app/shared/constants.dart

class Constants {
  static final String defaultDIDMethod = 'tz';
  static final String databaseFilename = 'wallet_tz.db';
}

par 

class Constants {
  static final String defaultDIDMethod = 'key';
  static final String databaseFilename = 'wallet_key.db';
}

pour avoir un did:key:Z6..... a la place du did:tz:tz1....

il faudrait verifier alors que la signature de la presentation ne plante pas !!!! avec le simulateur

Si cela fonctionne il faudra integrer cette option dans un menu, a discuter.....
d'autre smethod comme "did:sol" (blockchain siolana) serait alors aussi possible

**Comment by hawkbee1** [comment]
Waiting for bug correction from credible

**Comment by ThierryThevenet** [comment]
voir comment on peut gerer le switch sans impliquer le user ????
si on peut eviter de faire 2 builds ce seraiot mieux..... ? passer un argument a l install ? ou bien une manip cachée sur smartphone qui permette de passer sur did:key, et eventuellement d'autres daileurs did:sol: did:pkh,...qui sont toutees dispos sur didkit de base

**Comment by ThierryThevenet** [comment]
je crois qu effectivement la bonne solution c 'est de prevoir 2 profils : 
Profi 1 =  avec did:tz (par defaut) 
Profil 2 :  avec did:key
Chaque profil a son propre wallet.db

Et prevoir dans les parametres un switch entre profil.

**Comment by ThierryThevenet** [comment]
**faire au plus simple parceque ce sera refait plus tard**
