### ISSUE TITLE
VC CertificateOfEmployment

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/talao-wallet#49]
ajouter dans l'affichage du VC la date d'émission issuanceDate (n 'afficher que la date du jout )

**Comment by ThierryThevenet** [comment]
il y a un probleme sur la date qui s affiche mal et qui semble fausse (issuancedate)

**Comment by hawkbee1** [comment]
Je vois une inversion mois-jours, c'est l'affichage américain.
