### ISSUE TITLE
IOS : Le menu bas de page n est pas affiché sur l ecran de detail l attestation

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/talao-wallet#53]
IOS : on ne peut plus revenir en arriere. ça bloque la navigfation

**Comment by hawkbee1** [comment]
Le menu du bas s'accompagne d'une notion de menu actif alors j'ai ajouté avec le titre une croix pour quitter la page (comme lors de la preview du credential.

**Comment by hawkbee1** [comment]
En fait il y a déjà une flèche de retour. On ne voyait pas la barre de titre car le titre était vide.
