### ISSUE TITLE
Credential manifest

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/talao-wallet#78]

**Comment by hawkbee1** [comment]
issuer dit : 
1/ je suis capable d'emetre tels VC... (liste)
2/ description des infos : quels types d'attributs
3/ contenu du VC : description des champs

=> on l'intégre dans le Offer.
Si openIdConnect => récupère un nom de domaine => recherche d'un fichier json (credential manifest) dans well-known folder.

@ThierryThevenet need link to those SSI norms

**Comment by ThierryThevenet** [comment]
voila le point d'ancrage du credntial manifest pour openID https://github.com/tlodderstedt/openid-connect-4-credential-issuance/blob/main/openid-connect-4-credential-issuance-1_0.md#server-metadata
Il ets donc dans le repertoir well-known du domaine.
Ensuite voir la spec https://identity.foundation/credential-manifest/

**Comment by ThierryThevenet** [comment]
Mais il faut que l on fasse le tri sur les spces et 
Ce module de traitement du credrential manifest sera réutilisé plus tard

**Comment by ThierryThevenet** [comment]
le credrential manifest est disponible sur .well_known/openid-configuration
On y accede si le type du credential n est pas disponible dans le wallet comme un template et dans ce cas on cherche si il y a un output descriptor associé a ce type

**Comment by ThierryThevenet** [comment]
voila un credential manifes https://talao.co/.well-known/openid-configuration dans lequel il y a une description du type PaymentCard.
Donc en gros lorsque le wallet ne dispose pas du template de PaymentCard il peut regarder dans le credential si il y a une description du display.
On en discute, il y a 2 ou 3 trucs a bien défuinir
la spec est la https://identity.foundation/credential-manifest/#output-descriptor

**Comment by ThierryThevenet** [comment]
a discuter si le credential manifest ne doit pas passé a coté du credential preview pour ce flow ce qui reglerait le probleme pour en particulier  le over18 qui necessite un emailpass. On trouverait mention de la necessité d envoyer l Emailpass dans  "Presentation Definition"

**Comment by ThierryThevenet** [comment]
le credentiaa manifest doit etre lu dans le credentialOffer cf https://github.com/TalaoDAO/wallet-interaction#issuer-implementation et le champ "manifest" du credential offer

Attention ce module sera ré-utilsé aussi dans "siopv2 pour issuer" et dans ce cas le manfest sera situé dans le openid-configuration file du root du serveur
