### ISSUE TITLE
Local list of registers used to check trusted issuers

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/talao-wallet#90]
avec un bouton "fair" toujours confiance a ce domaine"

**Comment by hawkbee1** [comment]
Mis de côté pour l'instant

**Comment by hawkbee1** [comment]
meeting notes: Registre : vérifier identité issuer => case à cocher du/des registres qu’il va utiliser.
=> Ajoute dans settings une case à cocher pour demande de validation des issuer (validation automatique ou non).
