### ISSUE TITLE
gestion des code retour en erreur du issuer/verifier

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/talao-wallet#91]
affichage sur le wallet. Voir la possibilité de disposer de messages types

**Comment by ThierryThevenet** [comment]
On a dit que l on gardait les cods retours http,
IL y a donc une liste a ajoure a la doc et prevoir dan sle fichier  delangues du téléphone les traductions
https://github.com/TalaoDAO/talao-wallet/blob/ThierryThevenet-patch-1/docs/talao_interaction_protocol.md#issuerverfier-return-codes-to-be-done

**Comment by ThierryThevenet** [comment]
il y a des problemes de comportement, a voir

**Comment by hawkbee1** [comment]
Superposition de 3 popup comme on peut le voir par la noirceur de l'écran autour des popup => 3 click pour passer

**Comment by ThierryThevenet** [comment]
pour les tests sur le GET https://talao.co/wallet/test/return_code_GET

**Comment by ThierryThevenet** [comment]
Sur la version IOS en prod, il n y a aucun traitement particulier des codes retours du serveur

**Comment by ThierryThevenet** [comment]
probleme de comprehension sur le probleme des code erreur vu du serveur
cf google doc
